// =====================================================================
//  PREGUNTAS — formato: { p: pregunta, c: respuesta correcta, i: [3 incorrectas] }
//  Las opciones se revuelven solas al mostrarse. Agrega todas las que quieras.
// =====================================================================

const PREGUNTAS = {
  medicina: [
    { p: "¿Cuántos huesos tiene el cuerpo humano adulto?", c: "206", i: ["186", "212", "230"] },
    { p: "¿Cuál es el hueso más largo del cuerpo?", c: "Fémur", i: ["Tibia", "Húmero", "Peroné"] },
    { p: "¿Cuál es el hueso más pequeño del cuerpo?", c: "Estribo", i: ["Yunque", "Martillo", "Hioides"] },
    { p: "¿Qué órgano produce la insulina?", c: "Páncreas", i: ["Hígado", "Bazo", "Riñón"] },
    { p: "¿Cuántas cavidades tiene el corazón humano?", c: "4", i: ["2", "3", "6"] },
    { p: "¿Qué vitamina produce la piel con la luz del sol?", c: "Vitamina D", i: ["Vitamina C", "Vitamina A", "Vitamina K"] },
    { p: "¿Cuál es el órgano más grande del cuerpo?", c: "La piel", i: ["El hígado", "Los pulmones", "El intestino"] },
    { p: "¿Cuál es el rango normal de glucosa en ayuno (mg/dL)?", c: "70–100", i: ["40–60", "120–160", "180–220"] },
    { p: "¿Qué células transportan el oxígeno en la sangre?", c: "Eritrocitos", i: ["Leucocitos", "Plaquetas", "Linfocitos"] },
    { p: "¿Qué tipo de sangre es el donador universal?", c: "O negativo", i: ["AB positivo", "A negativo", "O positivo"] },
    { p: "¿Qué órgano produce la bilis?", c: "Hígado", i: ["Vesícula biliar", "Páncreas", "Estómago"] },
    { p: "¿Cuál es la frecuencia cardiaca normal en reposo de un adulto?", c: "60–100 lpm", i: ["30–50 lpm", "110–140 lpm", "150–180 lpm"] },
    { p: "¿Qué descubrió Alexander Fleming en 1928?", c: "La penicilina", i: ["La insulina", "La vacuna de la viruela", "Los rayos X"] },
    { p: "¿Qué parte del encéfalo coordina el equilibrio?", c: "Cerebelo", i: ["Hipotálamo", "Bulbo raquídeo", "Lóbulo frontal"] },
    { p: "¿Qué es la taquicardia?", c: "Frecuencia cardiaca mayor a 100 lpm", i: ["Frecuencia menor a 60 lpm", "Presión arterial alta", "Falta de oxígeno"] },
    { p: "¿Qué glándula produce la tiroxina (T4)?", c: "Tiroides", i: ["Hipófisis", "Suprarrenal", "Timo"] },
    { p: "¿Qué parásito causa la malaria?", c: "Plasmodium", i: ["Giardia", "Toxoplasma", "Trypanosoma"] },
    { p: "¿Cuál es la unidad funcional del riñón?", c: "Nefrona", i: ["Alvéolo", "Neurona", "Hepatocito"] },
    { p: "¿Qué válvula separa la aurícula y el ventrículo izquierdos?", c: "Mitral", i: ["Tricúspide", "Aórtica", "Pulmonar"] },
    { p: "¿Cuál es el nervio más largo del cuerpo?", c: "Ciático", i: ["Vago", "Femoral", "Radial"] },
    { p: "¿Qué mide un esfigmomanómetro?", c: "La presión arterial", i: ["La temperatura", "La glucosa", "La saturación de oxígeno"] },
    { p: "¿La falta de qué vitamina causa el escorbuto?", c: "Vitamina C", i: ["Vitamina B12", "Vitamina D", "Vitamina E"] },
    { p: "¿Cuál es la arteria más grande del cuerpo?", c: "Aorta", i: ["Carótida", "Femoral", "Pulmonar"] },
    { p: "¿Cuántos pares de nervios craneales hay?", c: "12", i: ["10", "31", "8"] },
    { p: "¿Dónde se absorbe la mayoría de los nutrientes?", c: "Intestino delgado", i: ["Estómago", "Intestino grueso", "Esófago"] },
    { p: "¿Qué células producen los anticuerpos?", c: "Linfocitos B", i: ["Linfocitos T", "Neutrófilos", "Eritrocitos"] },
    { p: "¿Cuántos pares de cromosomas tiene el ser humano?", c: "23", i: ["22", "24", "46"] },
    { p: "¿Qué virus causa el SIDA?", c: "VIH", i: ["VPH", "VHB", "Epstein-Barr"] },
    { p: "¿Con qué otro nombre se conoce al paracetamol?", c: "Acetaminofén", i: ["Ibuprofeno", "Ácido acetilsalicílico", "Naproxeno"] },
    { p: "¿Qué maniobra se usa ante un atragantamiento?", c: "Heimlich", i: ["Valsalva", "Epley", "Trendelenburg"] },
    { p: "En RCP de adulto, ¿cuál es la relación compresiones:ventilaciones?", c: "30:2", i: ["15:1", "5:1", "50:5"] },
    { p: "¿Qué hormona eleva la glucosa en sangre?", c: "Glucagón", i: ["Insulina", "Oxitocina", "Melatonina"] },
    { p: "¿Qué es la hipoglucemia?", c: "Glucosa baja en sangre", i: ["Glucosa alta en sangre", "Presión baja", "Falta de hierro"] },
    { p: "¿Dónde se lleva a cabo el intercambio de gases en el pulmón?", c: "Alvéolos", i: ["Bronquios", "Tráquea", "Pleura"] },
    { p: "¿Qué hueso protege el cerebro?", c: "Cráneo", i: ["Esternón", "Escápula", "Atlas"] },
  ],

  estoicismo: [
    { p: "¿Quién escribió 'Meditaciones'?", c: "Marco Aurelio", i: ["Séneca", "Epicteto", "Platón"] },
    { p: "Marco Aurelio fue emperador de…", c: "Roma", i: ["Grecia", "Persia", "Egipto"] },
    { p: "¿Quién escribió las 'Cartas a Lucilio'?", c: "Séneca", i: ["Cicerón", "Marco Aurelio", "Epicteto"] },
    { p: "Antes de ser filósofo, Epicteto fue…", c: "Esclavo", i: ["Soldado", "Emperador", "Senador"] },
    { p: "¿Quién fundó la escuela estoica?", c: "Zenón de Citio", i: ["Sócrates", "Aristóteles", "Diógenes"] },
    { p: "El nombre 'estoicismo' viene de la Stoa Poikile, que era…", c: "Un pórtico pintado de Atenas", i: ["Un templo en Roma", "Una montaña sagrada", "El nombre de un barco"] },
    { p: "¿Cómo se llama el manual breve con las enseñanzas de Epicteto?", c: "Enquiridión", i: ["Organon", "Leviatán", "Banquete"] },
    { p: "Séneca fue tutor y consejero de qué emperador?", c: "Nerón", i: ["Calígula", "Augusto", "Trajano"] },
    { p: "¿Qué significa 'memento mori'?", c: "Recuerda que morirás", i: ["Vive el momento", "Ama tu destino", "Conócete a ti mismo"] },
    { p: "¿Qué significa 'amor fati'?", c: "Amor al destino", i: ["Amor a la sabiduría", "Miedo a la muerte", "Amor al poder"] },
    { p: "La 'dicotomía del control' se asocia sobre todo a…", c: "Epicteto", i: ["Platón", "Nietzsche", "Kant"] },
    { p: "¿Quién escribió 'El obstáculo es el camino'?", c: "Ryan Holiday", i: ["Jordan Peterson", "Robin Sharma", "Mark Manson"] },
    { p: "¿Cuáles son las cuatro virtudes estoicas?", c: "Sabiduría, justicia, coraje y templanza", i: ["Fe, esperanza, caridad y paz", "Fuerza, riqueza, fama y poder", "Amor, odio, miedo y deseo"] },
    { p: "¿Quién sucedió a Zenón al frente de la escuela estoica?", c: "Cleantes", i: ["Crisipo", "Epicuro", "Pitágoras"] },
    { p: "¿A qué estoico se le llama el 'segundo fundador' de la escuela?", c: "Crisipo", i: ["Cleantes", "Séneca", "Posidonio"] },
    { p: "Según Séneca en 'Sobre la brevedad de la vida'…", c: "La vida no es corta, la desperdiciamos", i: ["La vida es demasiado corta para todo", "Hay que vivir rápido", "Solo los ricos viven bien"] },
    { p: "¿En qué idioma escribió Marco Aurelio sus 'Meditaciones'?", c: "Griego", i: ["Latín", "Arameo", "Egipcio"] },
    { p: "¿Quién fue el maestro de Epicteto?", c: "Musonio Rufo", i: ["Séneca", "Sócrates", "Zenón"] },
    { p: "¿En qué película aparece Marco Aurelio como personaje?", c: "Gladiador", i: ["300", "Troya", "Ben-Hur"] },
    { p: "'No nos perturban las cosas, sino nuestras opiniones sobre ellas.' ¿De quién es?", c: "Epicteto", i: ["Confucio", "Buda", "Aristóteles"] },
    { p: "¿Quién escribió 'El arte de la buena vida' (A Guide to the Good Life)?", c: "William B. Irvine", i: ["Ryan Holiday", "Massimo Pigliucci", "Alain de Botton"] },
    { p: "¿Cómo murió Séneca?", c: "Obligado a suicidarse por Nerón", i: ["En batalla", "De viejo en su casa", "Envenenado por su esposa"] },
    { p: "¿Qué es la 'premeditatio malorum'?", c: "Imaginar de antemano lo malo que puede pasar", i: ["Meditar por las mañanas", "Castigar a los malos", "Planear la venganza"] },
    { p: "¿Quién escribió 'Cómo ser un estoico'?", c: "Massimo Pigliucci", i: ["Ryan Holiday", "Epicteto", "Donald Robertson"] },
    { p: "Para los estoicos, la 'apatheia' es…", c: "Estar libre de pasiones que perturban", i: ["No sentir nada nunca", "Ser flojo", "Odiar a los demás"] },
    { p: "¿Qué filósofo estoico fue esclavo y cojeaba?", c: "Epicteto", i: ["Séneca", "Catón", "Zenón"] },
  ],

  programacion: [
    { p: "¿Qué significa HTML?", c: "HyperText Markup Language", i: ["High Tech Modern Language", "HyperTool Multi Language", "Home Text Markup Logic"] },
    { p: "¿Para qué sirve CSS?", c: "Para dar estilo y diseño a una página", i: ["Para guardar datos", "Para programar servidores", "Para comprimir imágenes"] },
    { p: "¿Qué lenguaje se ejecuta directamente en el navegador?", c: "JavaScript", i: ["Java", "C++", "Python"] },
    { p: "¿Qué comando de git guarda los cambios en el historial?", c: "git commit", i: ["git save", "git push", "git store"] },
    { p: "¿Qué comando de git sube tus commits a GitHub?", c: "git push", i: ["git upload", "git pull", "git send"] },
    { p: "¿Qué hace 'git clone'?", c: "Copia un repositorio a tu computadora", i: ["Borra un repositorio", "Crea una rama", "Junta dos ramas"] },
    { p: "En la mayoría de lenguajes, ¿qué índice tiene el primer elemento de un arreglo?", c: "0", i: ["1", "-1", "Depende del día"] },
    { p: "¿Cómo se imprime algo en pantalla en Python?", c: "print()", i: ["echo()", "console.log()", "printf()"] },
    { p: "¿Qué significa el error HTTP 404?", c: "No encontrado", i: ["Error del servidor", "Acceso prohibido", "Todo bien"] },
    { p: "¿Qué significa el error HTTP 500?", c: "Error interno del servidor", i: ["Página no encontrada", "No autorizado", "Redirección"] },
    { p: "¿Qué tipo de dato guarda verdadero o falso?", c: "Booleano", i: ["Entero", "Cadena", "Flotante"] },
    { p: "¿Para qué sirve SQL?", c: "Para consultar y manejar bases de datos", i: ["Para hacer páginas web", "Para editar fotos", "Para hacer videojuegos"] },
    { p: "En JavaScript, ¿qué hace '==='?", c: "Compara valor y tipo", i: ["Asigna un valor", "Compara solo el valor", "Suma tres veces"] },
    { p: "¿Cuánto es 5 en binario?", c: "101", i: ["110", "111", "100"] },
    { p: "¿Quién creó Python?", c: "Guido van Rossum", i: ["Linus Torvalds", "Bill Gates", "James Gosling"] },
    { p: "¿Quién creó el núcleo de Linux?", c: "Linus Torvalds", i: ["Richard Stallman", "Steve Jobs", "Dennis Ritchie"] },
    { p: "¿Qué etiqueta HTML se usa para un enlace?", c: "<a>", i: ["<link>", "<href>", "<url>"] },
    { p: "¿Qué etiqueta HTML muestra una imagen?", c: "<img>", i: ["<image>", "<pic>", "<src>"] },
    { p: "¿Qué significa JSON?", c: "JavaScript Object Notation", i: ["Java Standard Output Network", "JavaScript Online Node", "Just Simple Object Names"] },
    { p: "Una pila (stack) funciona como…", c: "LIFO: el último en entrar es el primero en salir", i: ["FIFO: el primero en entrar sale primero", "Orden alfabético", "Al azar"] },
    { p: "Una cola (queue) funciona como…", c: "FIFO: el primero en entrar es el primero en salir", i: ["LIFO: el último en entrar sale primero", "Por prioridad siempre", "Al azar"] },
    { p: "¿Qué lenguaje recomienda Google para apps de Android?", c: "Kotlin", i: ["Swift", "Ruby", "PHP"] },
    { p: "En CSS, ¿qué propiedad cambia el color del texto?", c: "color", i: ["font-color", "text-color", "background"] },
    { p: "¿Cuál es la complejidad de la búsqueda binaria?", c: "O(log n)", i: ["O(n)", "O(n²)", "O(1)"] },
    { p: "¿Qué pasa con la memoria RAM al apagar la computadora?", c: "Se borra (es volátil)", i: ["Se guarda para siempre", "Se pasa al monitor", "Se duplica"] },
    { p: "¿Qué es una API?", c: "Una interfaz para que programas se comuniquen", i: ["Un tipo de virus", "Un lenguaje de programación", "Una tarjeta de video"] },
    { p: "En JavaScript, ¿con qué palabra se declara una constante?", c: "const", i: ["let", "var", "final"] },
    { p: "¿Cuál es el puerto por defecto de HTTPS?", c: "443", i: ["80", "21", "8080"] },
    { p: "¿Qué empresa creó originalmente Java?", c: "Sun Microsystems", i: ["Microsoft", "Oracle", "IBM"] },
    { p: "¿Qué es un 'bug'?", c: "Un error en el programa", i: ["Una función nueva", "Un tipo de servidor", "Un lenguaje"] },
    { p: "¿Qué es una variable?", c: "Un espacio con nombre para guardar un valor", i: ["Un error de sintaxis", "Un tipo de bucle", "Un archivo de texto"] },
    { p: "¿Qué estructura repite instrucciones mientras se cumpla una condición?", c: "while", i: ["if", "switch", "return"] },
    { p: "¿Qué significa CPU?", c: "Unidad Central de Procesamiento", i: ["Computadora Personal Única", "Control de Puertos USB", "Centro de Programas Útiles"] },
  ],

  general: [
    { p: "¿Cuál es la capital de Japón?", c: "Tokio", i: ["Kioto", "Osaka", "Hiroshima"] },
    { p: "¿Qué planeta es conocido como el planeta rojo?", c: "Marte", i: ["Venus", "Júpiter", "Saturno"] },
    { p: "¿Cuál es el océano más grande?", c: "Pacífico", i: ["Atlántico", "Índico", "Ártico"] },
    { p: "¿Quién pintó la Mona Lisa?", c: "Leonardo da Vinci", i: ["Picasso", "Van Gogh", "Miguel Ángel"] },
    { p: "¿Cuál es el animal más grande del mundo?", c: "Ballena azul", i: ["Elefante africano", "Tiburón ballena", "Jirafa"] },
    { p: "¿En qué estado de México está Tijuana?", c: "Baja California", i: ["Sonora", "Sinaloa", "Baja California Sur"] },
    { p: "¿Qué significa 'arigatō' en japonés?", c: "Gracias", i: ["Hola", "Adiós", "Perdón"] },
    { p: "¿Cuántos lados tiene un hexágono?", c: "6", i: ["5", "7", "8"] },
    { p: "¿En qué año llegó Colón a América?", c: "1492", i: ["1521", "1810", "1453"] },
    { p: "¿En qué año inició la Independencia de México?", c: "1810", i: ["1821", "1910", "1776"] },
    { p: "¿Quién escribió 'Don Quijote de la Mancha'?", c: "Miguel de Cervantes", i: ["Lope de Vega", "Gabriel García Márquez", "Federico García Lorca"] },
    { p: "¿Quién escribió 'Cien años de soledad'?", c: "Gabriel García Márquez", i: ["Octavio Paz", "Mario Vargas Llosa", "Juan Rulfo"] },
    { p: "¿Qué metal es líquido a temperatura ambiente?", c: "Mercurio", i: ["Plomo", "Aluminio", "Estaño"] },
    { p: "¿Cuál es el símbolo químico del oro?", c: "Au", i: ["Ag", "Or", "Go"] },
    { p: "¿Cuál es el símbolo químico del hierro?", c: "Fe", i: ["Hi", "Ir", "F"] },
    { p: "¿Cuál es el país más poblado del mundo?", c: "India", i: ["China", "Estados Unidos", "Indonesia"] },
    { p: "¿Cuál es la moneda de Japón?", c: "Yen", i: ["Won", "Yuan", "Baht"] },
    { p: "¿Cuál es la montaña más alta del mundo?", c: "Everest", i: ["K2", "Aconcagua", "Kilimanjaro"] },
    { p: "¿Cuál es el planeta más grande del sistema solar?", c: "Júpiter", i: ["Saturno", "Neptuno", "Tierra"] },
    { p: "¿Cuál es el planeta más cercano al Sol?", c: "Mercurio", i: ["Venus", "Marte", "Tierra"] },
    { p: "¿A qué velocidad viaja aproximadamente la luz?", c: "300,000 km/s", i: ["30,000 km/s", "3,000 km/s", "1,000,000 km/s"] },
    { p: "¿Quién propuso la teoría de la relatividad?", c: "Albert Einstein", i: ["Isaac Newton", "Nikola Tesla", "Stephen Hawking"] },
    { p: "¿Qué gas abunda más en la atmósfera terrestre?", c: "Nitrógeno", i: ["Oxígeno", "Dióxido de carbono", "Hidrógeno"] },
    { p: "¿Cuál es la capital de Canadá?", c: "Ottawa", i: ["Toronto", "Vancouver", "Montreal"] },
    { p: "¿Cuál es la capital de Australia?", c: "Canberra", i: ["Sídney", "Melbourne", "Perth"] },
    { p: "¿Cuántas entidades federativas tiene México?", c: "32", i: ["31", "30", "33"] },
    { p: "¿Cuántos días tiene un año bisiesto?", c: "366", i: ["365", "364", "360"] },
    { p: "¿En qué país están las pirámides de Giza?", c: "Egipto", i: ["México", "Perú", "Sudán"] },
    { p: "¿Quién escribió 'Romeo y Julieta'?", c: "William Shakespeare", i: ["Charles Dickens", "Oscar Wilde", "Dante Alighieri"] },
    { p: "¿Quién fue el primer ser humano en pisar la Luna?", c: "Neil Armstrong", i: ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins"] },
    { p: "¿En qué año cayó el Muro de Berlín?", c: "1989", i: ["1991", "1979", "1945"] },
    { p: "¿Quién pintó 'La noche estrellada'?", c: "Vincent van Gogh", i: ["Claude Monet", "Salvador Dalí", "Diego Rivera"] },
    { p: "¿Quién pintó el 'Guernica'?", c: "Pablo Picasso", i: ["Joan Miró", "Francisco de Goya", "Salvador Dalí"] },
    { p: "¿Cuántas teclas tiene un piano estándar?", c: "88", i: ["76", "64", "100"] },
    { p: "¿Qué arma usaban tradicionalmente los samuráis?", c: "Katana", i: ["Cimitarra", "Florete", "Machete"] },
    { p: "¿Cuántos jugadores por equipo hay en la cancha en el fútbol?", c: "11", i: ["10", "9", "12"] },
    { p: "Contando 2026, ¿cuántos Mundiales de fútbol ha recibido México?", c: "3", i: ["2", "1", "4"] },
    { p: "¿Qué pintora mexicana es famosa por sus autorretratos?", c: "Frida Kahlo", i: ["Remedios Varo", "Leonora Carrington", "María Izquierdo"] },
    { p: "¿Qué gas absorben las plantas para la fotosíntesis?", c: "Dióxido de carbono", i: ["Oxígeno", "Nitrógeno", "Helio"] },
    { p: "¿Cuál es la lengua con más hablantes nativos?", c: "Chino mandarín", i: ["Inglés", "Español", "Hindi"] },
    { p: "¿Cuál es la capital de Italia?", c: "Roma", i: ["Milán", "Venecia", "Florencia"] },
    { p: "¿En qué continente está Egipto?", c: "África", i: ["Asia", "Europa", "Oceanía"] },
    { p: "¿Cuántos minutos tiene un día?", c: "1,440", i: ["1,200", "3,600", "1,000"] },
    { p: "¿Qué instrumento mide los sismos?", c: "Sismógrafo", i: ["Barómetro", "Termómetro", "Anemómetro"] },
  ],
};

// Qué temas le tocan a cada quien en cada partida (5 preguntas en total).
const TEMAS_POR_USUARIO = {
  julian:   { nombre: "Medicina", mezcla: [["medicina", 5]] },
  esteban:  { nombre: "Conocimiento general", mezcla: [["general", 5]] },
  derek:    { nombre: "Estoicismo y cultura general", mezcla: [["estoicismo", 3], ["general", 2]] },
  gilberto: { nombre: "Programación y cultura general", mezcla: [["programacion", 3], ["general", 2]] },
};
